### ISSUE TITLE
Unable to run — lack of requeriments and documentation

### ISSUE THREAD

**Issue by JaimeObregon** [olithissen/MonkeyBusiness#1]
My only experience with Java was brief, dating back 22 years, and unfortunately, I could not find instructions or documentation on how to run this project.

I installed Maven and ran `mvn compile`, which created a `target` directory, what seems correct.

However, running it on my macOS' CLI was unsuccessful:

```console
$ java -cp target/classes net.tonick.monkeybusiness.App "/tmp/MonkeyIsland1/monkey/MONKEY.00"
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/tonick/monkeybusiness/App has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:635)
```

This error suggests that the project was compiled with a newer Java version than the one running it (Java 8, which supports up to class file version 52.0).

My system's Java version:

```console
$ java -version
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.391-b13, mixed mode)
```

After installing OpenJDK version 21:

```console
$ /opt/homebrew/opt/openjdk@21/bin/java -version
openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment Homebrew (build 21.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.1, mixed mode, sharing)
```

Running the application with OpenJDK 21 resulted in a different error:

```console
$ /opt/homebrew/opt/openjdk@21/bin/java -cp target/classes net.tonick.monkeybusiness.App "/tmp/MonkeyIsland1/monkey/MONKEY.00"
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at net.tonick.monkeybusiness.App.<clinit>(App.java:21)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 1 more
```

This error indicates a missing dependency, `org.apache.logging.log4j`, which suggests that the classpath might not include all necessary dependencies.

Also, I'd suggest adding a link to [A Deep Dive into the SCUMM Bytecode](https://tonick.net/p/2021/03/a-deep-dive-into-the-scumm-bytecode/) in the `README.md` for context.

**Comment by olithissen** [comment]
Hallo Jaime and thank you for your input!

I hacked this one down over the holidays a few years back, never thinking that someone might actually try it :-) So just now I pulled the project up to Java 21 and added maven-assembly to build a fat-jar with all necessary dependencies. 

Try pulling the current revision now and tell me if the (still very short) documentation is sufficient.

All the best
Oli

**Comment by JaimeObregon** [comment]
Thank you so much, @olithissen, for your swift and helpful response!

I'm thrilled to share that, with your assistance, I've successfully extracted all the quotes from the Spanish version of The Secret of Monkey Island. 🎉 What a feeling! Here they are: https://gist.github.com/JaimeObregon/f50364311e70fb2dd8254190b25a3665

Additionally, thank you for merging #2.

Wishing you an amazing day ahead!

**Comment by olithissen** [comment]
Anything cool you're planning to do with them? Besides the obvious: Setting up a Spanish Monkey Island Quote bot (https://github.com/olithissen/monkeyislandbot_mastodon)

**Comment by JaimeObregon** [comment]
Not for the moment, my friend. Currently I'm just delving into the universe of SCUMM-based games, driven purely by curiosity. This journey has rekindled a deep sense of nostalgia for the nineties IBM PC era. If you share this fascination, I highly recommend visiting [Thimbleweed Park's website](https://thimbleweedpark.com/), especially its insightful development blog. Also, you may enjoy [Thimbleweed Park Kickstarter page](https://www.kickstarter.com/projects/thimbleweedpark/thimbleweed-park-a-new-classic-point-and-click-adv). And for a real treat, check out [these engaging videos](https://vimeo.com/grumpygamer), particularly the first ones. Most of these have been created by Ron Gilbert himself and offer a unique glimpse into the game development process. <3

Thank you, Oli!
